"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

# Configure PyMySQL as MySQLdb client for Django with version check patch
try:
    import pymysql
    pymysql.version_info = (2, 2, 6, "final", 0)
    pymysql.install_as_MySQLdb()
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-+g!87#jdpv#3=m715hs%hp_7$9k+0al)%hto9+bb9vf8rmj69@'
)

# SECURITY WARNING: don't run with debug turned on in production!
is_render = os.getenv('RENDER') is not None
default_debug = 'False' if is_render else 'True'
DEBUG = os.getenv('DEBUG', default_debug).lower() in ('true', '1', 'yes')

# Allowed Hosts
allowed_hosts_env = os.getenv('ALLOWED_HOSTS', '')
if allowed_hosts_env:
    ALLOWED_HOSTS = [h.strip() for h in allowed_hosts_env.split(',') if h.strip()]
    if '.onrender.com' not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append('.onrender.com')
else:
    ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'chats',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must be at the top
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# ==============================================================================
# Database Configuration - Persistent MySQL with Cloud & Local Support
# ==============================================================================
# Priority:
# 1. DATABASE_URL / MYSQL_URL (e.g. Aiven MySQL, PlanetScale, AWS RDS, Railway)
# 2. Individual env variables: DB_NAME/MYSQL_DATABASE, DB_USER, DB_PASSWORD, DB_HOST, DB_PORT
# 3. Local fallback to SQLite if no MySQL server is reachable or configured

def _test_db_connectivity(config):
    """Test whether the configured database is actually reachable."""
    engine = config.get('ENGINE', '')
    host = config.get('HOST', '')
    if not host or host in ('localhost', '127.0.0.1') and 'sqlite' in engine:
        return True, None

    if 'mysql' in engine:
        try:
            import pymysql
            port = int(config.get('PORT') or 3306)
            user = config.get('USER') or 'root'
            passwd = config.get('PASSWORD') or ''
            db = config.get('NAME') or ''
            ssl_opt = config.get('OPTIONS', {}).get('ssl')
            conn = pymysql.connect(
                host=host,
                port=port,
                user=user,
                password=passwd,
                database=db,
                connect_timeout=4,
                ssl=ssl_opt if ssl_opt else None
            )
            conn.close()
            return True, None
        except Exception as exc:
            return False, f"MySQL connection test failed ({host}:{port}): {exc}"

    elif 'postgres' in engine:
        try:
            import psycopg2
            port = int(config.get('PORT') or 5432)
            user = config.get('USER') or 'postgres'
            passwd = config.get('PASSWORD') or ''
            db = config.get('NAME') or ''
            conn = psycopg2.connect(
                host=host,
                port=port,
                user=user,
                password=passwd,
                dbname=db,
                connect_timeout=4
            )
            conn.close()
            return True, None
        except Exception as exc:
            return False, f"PostgreSQL connection test failed ({host}:{port}): {exc}"

    return True, None

database_url = os.getenv('DATABASE_URL') or os.getenv('MYSQL_URL')
target_db = None

if database_url:
    try:
        db_config = dj_database_url.config(
            default=database_url,
            conn_max_age=0,
        )
        if 'mysql' in db_config.get('ENGINE', ''):
            db_config.setdefault('OPTIONS', {})
            db_config['OPTIONS']['charset'] = 'utf8mb4'
            if not db_config.get('NAME'):
                db_config['NAME'] = 'defaultdb'
            
            ssl_mode = db_config['OPTIONS'].pop('ssl-mode', None) or db_config['OPTIONS'].pop('ssl_mode', None)
            host = db_config.get('HOST', '')
            if ssl_mode or os.getenv('DB_SSL', 'true').lower() in ('true', '1', 'yes', 'required') or (host and host not in ('localhost', '127.0.0.1')):
                if 'ssl' not in db_config['OPTIONS']:
                    db_config['OPTIONS']['ssl'] = {}

        is_ok, err_msg = _test_db_connectivity(db_config)
        if is_ok:
            target_db = db_config
        else:
            print(f"[DB Notice] {err_msg} -> Falling back to SQLite.")
    except Exception as e:
        print(f"[DB Notice] Error parsing DATABASE_URL: {e} -> Falling back to SQLite.")
else:
    # Check individual MySQL credentials
    db_name = os.getenv('DB_NAME') or os.getenv('MYSQL_DATABASE') or os.getenv('MYSQLDATABASE')
    db_user = os.getenv('DB_USER') or os.getenv('MYSQL_USER') or os.getenv('MYSQLUSER')
    db_password = os.getenv('DB_PASSWORD') or os.getenv('MYSQL_PASSWORD') or os.getenv('MYSQLPASSWORD')
    db_host = os.getenv('DB_HOST') or os.getenv('MYSQL_HOST') or os.getenv('MYSQLHOST')
    db_port = os.getenv('DB_PORT') or os.getenv('MYSQL_PORT') or os.getenv('MYSQLPORT', '3306')

    if db_host and db_name:
        db_options = {'charset': 'utf8mb4'}
        if db_host not in ('localhost', '127.0.0.1') or os.getenv('DB_SSL', '').lower() in ('true', '1', 'yes', 'required'):
            db_options['ssl'] = {}

        my_config = {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': db_name,
            'USER': db_user or 'root',
            'PASSWORD': db_password or '',
            'HOST': db_host,
            'PORT': int(db_port),
            'OPTIONS': db_options,
            'CONN_MAX_AGE': 0,
        }
        is_ok, err_msg = _test_db_connectivity(my_config)
        if is_ok:
            target_db = my_config
        else:
            print(f"[DB Notice] {err_msg} -> Falling back to SQLite.")

if target_db:
    DATABASES = {'default': target_db}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
os.makedirs(STATIC_ROOT, exist_ok=True)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}
WHITENOISE_MANIFEST_STRICT = False

# Media files (for uploaded documents)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==============================================================================
# CORS & CSRF Configuration
# ==============================================================================

CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'False').lower() in ('true', '1', 'yes')

# Read frontend and CORS allowed origins from environment
frontend_url_env = os.getenv('FRONTEND_URL', '')
cors_origins_env = os.getenv('CORS_ALLOWED_ORIGINS', '')

default_origins = [
    'https://chatdocgpt.online',
    'https://www.chatdocgpt.online',
    'http://chatdocgpt.online',
    'http://www.chatdocgpt.online',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]
if frontend_url_env:
    for u in frontend_url_env.split(','):
        if u.strip():
            default_origins.append(u.strip().rstrip('/'))

if cors_origins_env:
    for u in cors_origins_env.split(','):
        if u.strip():
            default_origins.append(u.strip().rstrip('/'))

CORS_ALLOWED_ORIGINS = list(dict.fromkeys(default_origins))
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https:\/\/.*\.chatdocgpt\.online$",
    r"^https:\/\/.*\.onrender\.com$",
]
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CSRF Trusted Origins
csrf_trusted_env = os.getenv('CSRF_TRUSTED_ORIGINS', '')
default_csrf = [
    'https://chatdocgpt.online',
    'https://www.chatdocgpt.online',
    'http://chatdocgpt.online',
    'http://www.chatdocgpt.online',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'https://*.onrender.com',
]
if frontend_url_env:
    for u in frontend_url_env.split(','):
        if u.strip():
            default_csrf.append(u.strip().rstrip('/'))

if csrf_trusted_env:
    for u in csrf_trusted_env.split(','):
        if u.strip():
            default_csrf.append(u.strip().rstrip('/'))

CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(default_csrf))


# ==============================================================================
# Logging Configuration
# ==============================================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'chats': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}


# Email configurations
if os.getenv('RENDER'):
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = os.getenv(
        'EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend'
    )
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'santhoshlogu1782003@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'woba jgwb uogd jizi')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
